# This file was generated by GoReleaser. DO NOT EDIT.
cask "azctx" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "ba821da18ef3acd9492ea16bca081f45c425bed92156f58bbc39a800154a0584"
      url "https://github.com/lvlcn-t/azctx/releases/download/v#{version}/azctx_Darwin_x86_64.tar.gz",
        verified: "github.com/lvlcn-t/azctx/releases/download"
    end
    on_arm do
      sha256 "dbabbb61ee4cf8fd98bcbc2340eed78027f2e429af8ef7ec0bf913f049cb5d0e"
      url "https://github.com/lvlcn-t/azctx/releases/download/v#{version}/azctx_Darwin_arm64.tar.gz",
        verified: "github.com/lvlcn-t/azctx/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "f4592e2e94abbe40e5cb315f17b182e6a9f125c8a3eed300050c320c676e777e"
      url "https://github.com/lvlcn-t/azctx/releases/download/v#{version}/azctx_Linux_x86_64.tar.gz",
        verified: "github.com/lvlcn-t/azctx/releases/download"
    end
    on_arm do
      sha256 "bcf897c647ca7d1d7adf4a777fae73dc0014d1599ac07b0d3dc653a8724f7423"
      url "https://github.com/lvlcn-t/azctx/releases/download/v#{version}/azctx_Linux_arm64.tar.gz",
        verified: "github.com/lvlcn-t/azctx/releases/download"
    end
  end

  name "azctx"
  desc "Faster way to switch between tenants and subscriptions with az"
  homepage "https://github.com/lvlcn-t/azctx"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "azure-cli",
    ]

  binary "azctx"
  bash_completion "completions/azctx.bash"
  fish_completion "completions/azctx.fish"
  zsh_completion "completions/azctx.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/azctx"]
    end
  end

  zap trash: [
      "~/Library/Application Support/azctx",
    ]

end
