# This file was generated by GoReleaser. DO NOT EDIT.
cask "azctx" do
  version "0.4.3"

  on_macos do
    on_arm do
      sha256 "d45166267d22453a56ab7200ca96f8a64d2848530bce5b5ee54c419e74d2986a"
      url "https://github.com/lvlcn-t/azctx/releases/download/v#{version}/azctx_Darwin_arm64.tar.gz",
        verified: "github.com/lvlcn-t/azctx/releases/download"
    end
    on_intel do
      sha256 "38075a316ba624c2f5aa093fce3a04b6c4394882a77575852f5d96c592a03e5e"
      url "https://github.com/lvlcn-t/azctx/releases/download/v#{version}/azctx_Darwin_x86_64.tar.gz",
        verified: "github.com/lvlcn-t/azctx/releases/download"
    end
  end
  on_linux do
    on_arm do
      sha256 "e2adb52bcaf83265d638fb8cfac3fe8f9ba019ae1b5ef469d5e2687a4f0cf996"
      url "https://github.com/lvlcn-t/azctx/releases/download/v#{version}/azctx_Linux_arm64.tar.gz",
        verified: "github.com/lvlcn-t/azctx/releases/download"
    end
    on_intel do
      sha256 "1994443175b0f20c3b47aafbc76dc9882c7be08e6806373c16b58d9a9ca4d854"
      url "https://github.com/lvlcn-t/azctx/releases/download/v#{version}/azctx_Linux_x86_64.tar.gz",
        verified: "github.com/lvlcn-t/azctx/releases/download"
    end
  end

  name "azctx"
  desc "Faster way to switch between tenants and subscriptions with az"
  homepage "https://github.com/lvlcn-t/azctx"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "azure-cli",
    ]

  binary "azctx"
  bash_completion "completions/azctx.bash"
  fish_completion "completions/azctx.fish"
  zsh_completion "completions/azctx.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/azctx"]
    end
  end

  zap trash: [
      "~/.config/azctx",
    ]

end
