# This file was generated by GoReleaser. DO NOT EDIT.
cask "azctx" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "54e088f8237e3da3f8f073a91875ef025b7a4a307c7860d4fb671e5e020fe90b"
      url "https://github.com/lvlcn-t/azctx/releases/download/v#{version}/azctx_Darwin_x86_64.tar.gz",
        verified: "github.com/lvlcn-t/azctx/releases/download"
    end
    on_arm do
      sha256 "7c26d45cf90c68e266089c33d26e681204aca7d00347405918fda20dad1f21df"
      url "https://github.com/lvlcn-t/azctx/releases/download/v#{version}/azctx_Darwin_arm64.tar.gz",
        verified: "github.com/lvlcn-t/azctx/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "bccc23461ba595794023a54531978271d872151559169716895a96449962b973"
      url "https://github.com/lvlcn-t/azctx/releases/download/v#{version}/azctx_Linux_x86_64.tar.gz",
        verified: "github.com/lvlcn-t/azctx/releases/download"
    end
    on_arm do
      sha256 "a745f010211ba32d839b78b089070b1dd3bb62d2fdfa141361e04ce281229e9a"
      url "https://github.com/lvlcn-t/azctx/releases/download/v#{version}/azctx_Linux_arm64.tar.gz",
        verified: "github.com/lvlcn-t/azctx/releases/download"
    end
  end

  name "azctx"
  desc "Faster way to switch between tenants and subscriptions with az"
  homepage "https://github.com/lvlcn-t/azctx"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "azure-cli",
    ]

  binary "azctx"
  bash_completion "completions/azctx.bash"
  fish_completion "completions/azctx.fish"
  zsh_completion "completions/azctx.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/azctx"]
    end
  end

  zap trash: [
      "~/.config/azctx",
    ]

end
